filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/access.log
      - /var/log/error.log
    fields:
      service: nginx
    fields_under_root: true

output.elasticsearch:
  hosts: ["http://opensearch:9200"]

setup.template.enabled: true

setup.kibana:
  host: "opensearch-dashboards:5601"
